### ISSUE TITLE
Assimp (asset import library) crashes code generator

### ISSUE THREAD

**Issue by DemiMarie** [google/sandboxed-api#97]
```
Traceback (most recent call last):
  File "/home/user/sandboxed-api/sandboxed_api/tools/generator2/sapi_generator.py", line 73, in <module>
    app.run(main)
  File "/usr/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/user/sandboxed-api/sandboxed_api/tools/generator2/sapi_generator.py", line 60, in main
    result = generator.generate(FLAGS.sapi_name, FLAGS.sapi_functions,
  File "/home/user/sandboxed-api/sandboxed_api/tools/generator2/code.py", line 729, in generate
    related_types = self._get_related_types(function_names)
  File "/home/user/sandboxed-api/sandboxed_api/tools/generator2/code.py", line 790, in _get_related_types
    types += sorted(r for r in fn_related_types if r not in processed)
  File "/home/user/sandboxed-api/sandboxed_api/tools/generator2/code.py", line 165, in __gt__
    self._tu.order[other._get_declaration().hash])  # pylint: disable=protected-access
KeyError: 3995101709
```

The key depends on the set of headers chosen.  Not all of the headers cause this, but many do.

**Comment by cblichmann** [comment]
Which specific headers cause this?

**Comment by DemiMarie** [comment]
`/usr/include/assimp/BaseImporter.h` for one
